export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//SIGNUP AND LOGIN
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
//BUSINESS
export const BUSINESS_LOADED = 'BUSINESS_LOADED';
export const BUSINESS_SAVE = 'BUSINESS_SAVE';
export const BUSINESS_FAIL = 'BUSINESS_FAIL';
//ACCOUNT
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED';
export const ACCOUNT_SAVE = 'ACCOUNT_SAVE';
export const ACCOUNT_FAIL = 'ACCOUNT_FAIL';
//SEARCH
export const SEARCH_LOADED = 'SEARCH_LOADED';
export const SEARCH_FAIL = 'SEARCH_FAIL';
