export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//SIGNUP AND LOGIN
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
//BUSINESS
export const BUSINESS_LOADED = 'BUSINESS_LOADED';
export const BUSINESS_SUCCESS = 'BUSINESS_SUCCESS';
export const BUSINESS__FAIL = 'BUSINESS__FAIL';

export const BUSINESS_LOADED_FAIL = 'BUSINESS_LOADED_FAIL';

export const BUSINESS_SAVE = 'BUSINESS_SAVE';
export const BUSINESS_SAVE_FAIL = 'BUSINESS_SAVE_FAIL';

export const BUSINESS_UPDATE = 'BUSINESS_UPDATE';
export const BUSINESS_UPDATE_FAIL = 'BUSINESS_UPDATE_FAIL';

export const BUSINESS_DELETE = 'BUSINESS_DELETE';
export const BUSINESS_DELETE_FAIL = 'BUSINESS_DELETE_FAIL';
//ACCOUNT
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED';
export const ACCOUNT_SAVE = 'ACCOUNT_SAVE';
export const ACCOUNT_FAIL = 'ACCOUNT_FAIL';

export const ACCOUNT_LOADED_FAIL = 'ACCOUNT_LOADED_FAIL';

export const ACCOUNT_SAVE_FAIL = 'ACCOUNT_SAVE_FAIL';

export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_UPDATE_FAIL = 'ACCOUNT_UPDATE_FAIL';

export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';
export const ACCOUNT_DELETE_FAIL = 'ACCOUNT_DELETE_FAIL';
//PROGRAM
export const PROGRAM_LOADED = 'PROGRAM_LOADED';
export const PROGRAM_SAVE = 'PROGRAM_SAVE';
export const PROGRAM_FAIL = 'PROGRAM_FAIL';

export const PROGRAM_LOADED_FAIL = 'PROGRAM_LOADED_FAIL';

export const PROGRAM_SAVE_FAIL = 'PROGRAM_SAVE_FAIL';

export const PROGRAM_UPDATE = 'PROGRAM_UPDATE';
export const PROGRAM_UPDATE_FAIL = 'PROGRAM_UPDATE_FAIL';

export const PROGRAM_DELETE = 'PROGRAM_DELETE';
export const PROGRAM_DELETE_FAIL = 'PROGRAM_DELETE_FAIL';
//TEAM
export const TEAM_LOADED = 'TEAM_LOADED';
export const TEAM_SAVE = 'TEAM_SAVE';
export const TEAM_FAIL = 'TEAM_FAIL';

export const TEAM_LOADED_FAIL = 'TEAM_LOADED_FAIL';

export const TEAM_SAVE_FAIL = 'TEAM_SAVE_FAIL';

export const TEAM_UPDATE = 'TEAM_UPDATE';
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL';

export const TEAM_DELETE = 'TEAM_DELETE';
export const TEAM_DELETE_FAIL = 'TEAM_DELETE_FAIL';
//SEARCH
export const SEARCH_LOADED = 'SEARCH_LOADED';
export const SEARCH_FAIL = 'SEARCH_FAIL';
